# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.word_input:QtWidgets.QLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.word_input.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.word_input.setObjectName("word_input")
        self.type_button:QtWidgets.QPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.type_button.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.type_button.setAutoFillBackground(False)
        self.type_button.setObjectName("type_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 47, 13))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 446, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.wordgrid:QtWidgets.QGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.wordgrid.setContentsMargins(0, 0, 0, 0)
        self.wordgrid.setObjectName("wordgrid")
        self.word_list:QtWidgets.QListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.word_list.setGeometry(QtCore.QRect(560, 70, 261, 571))
        self.word_list.setObjectName("word_list")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.restart_button:QtWidgets.QPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(800, 10, 75, 23))
        self.restart_button.setObjectName("restart_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.type_button.setText(_translate("MainWindow", "TYPE"))
        self.label.setText(_translate("MainWindow", "WORD"))
        self.label_2.setText(_translate("MainWindow", "WORD LIST"))
        self.restart_button.setText(_translate("MainWindow", "RESTART"))
